
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiic.h"

/*
* The configuration table for devices
*/

XIic_Config XIic_ConfigTable[XPAR_XIIC_NUM_INSTANCES] =
{
	{
		XPAR_ZED_HDMI_IIC_0_DEVICE_ID,
		XPAR_ZED_HDMI_IIC_0_BASEADDR,
		XPAR_ZED_HDMI_IIC_0_TEN_BIT_ADR,
		XPAR_ZED_HDMI_IIC_0_GPO_WIDTH
	}
};


