
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_RESET_SEL_AXIS_DEVICE_ID,
		XPAR_RGB_TO_YUV422_RESET_SEL_AXIS_BASEADDR,
		XPAR_RGB_TO_YUV422_RESET_SEL_AXIS_INTERRUPT_PRESENT,
		XPAR_RGB_TO_YUV422_RESET_SEL_AXIS_IS_DUAL
	}
};


