
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_csc.h"

/*
* The configuration table for devices
*/

XV_csc_Config XV_csc_ConfigTable[XPAR_XV_CSC_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_CSC_DEVICE_ID,
		XPAR_RGB_TO_YUV422_CSC_S_AXI_CTRL_BASEADDR,
		XPAR_RGB_TO_YUV422_CSC_SAMPLES_PER_CLOCK,
		XPAR_RGB_TO_YUV422_CSC_V_CSC_MAX_WIDTH,
		XPAR_RGB_TO_YUV422_CSC_V_CSC_MAX_HEIGHT,
		XPAR_RGB_TO_YUV422_CSC_MAX_DATA_WIDTH,
		XPAR_RGB_TO_YUV422_CSC_ENABLE_422,
		XPAR_RGB_TO_YUV422_CSC_ENABLE_420,
		XPAR_RGB_TO_YUV422_CSC_ENABLE_WINDOW
	}
};


