
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxis_switch.h"

/*
* The configuration table for devices
*/

XAxis_Switch_Config XAxis_Switch_ConfigTable[XPAR_XAXIS_SWITCH_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_VIDEO_ROUTER_XBAR_DEVICE_ID,
		XPAR_RGB_TO_YUV422_VIDEO_ROUTER_XBAR_BASEADDR,
		XPAR_RGB_TO_YUV422_VIDEO_ROUTER_XBAR_NUM_SI,
		XPAR_RGB_TO_YUV422_VIDEO_ROUTER_XBAR_NUM_MI
	}
};


