
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_letterbox.h"

/*
* The configuration table for devices
*/

XV_letterbox_Config XV_letterbox_ConfigTable[XPAR_XV_LETTERBOX_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_LTR_DEVICE_ID,
		XPAR_RGB_TO_YUV422_LTR_S_AXI_CTRL_BASEADDR,
		XPAR_RGB_TO_YUV422_LTR_SAMPLES_PER_CLOCK,
		XPAR_RGB_TO_YUV422_LTR_NUM_VIDEO_COMPONENTS,
		XPAR_RGB_TO_YUV422_LTR_MAX_COLS,
		XPAR_RGB_TO_YUV422_LTR_MAX_ROWS,
		XPAR_RGB_TO_YUV422_LTR_MAX_DATA_WIDTH
	}
};


