
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_hcresampler.h"

/*
* The configuration table for devices
*/

XV_hcresampler_Config XV_hcresampler_ConfigTable[XPAR_XV_HCRESAMPLER_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_HCR_DEVICE_ID,
		XPAR_RGB_TO_YUV422_HCR_S_AXI_CTRL_BASEADDR,
		XPAR_RGB_TO_YUV422_HCR_SAMPLES_PER_CLOCK,
		XPAR_RGB_TO_YUV422_HCR_MAX_COLS,
		XPAR_RGB_TO_YUV422_HCR_MAX_ROWS,
		XPAR_RGB_TO_YUV422_HCR_MAX_DATA_WIDTH,
		XPAR_RGB_TO_YUV422_HCR_CONVERT_TYPE,
		XPAR_RGB_TO_YUV422_HCR_NUM_H_TAPS
	}
};


