
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_vscaler.h"

/*
* The configuration table for devices
*/

XV_vscaler_Config XV_vscaler_ConfigTable[XPAR_XV_VSCALER_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_VSC_DEVICE_ID,
		XPAR_RGB_TO_YUV422_VSC_S_AXI_CTRL_BASEADDR,
		XPAR_RGB_TO_YUV422_VSC_SAMPLES_PER_CLOCK,
		XPAR_RGB_TO_YUV422_VSC_NUM_VIDEO_COMPONENTS,
		XPAR_RGB_TO_YUV422_VSC_MAX_COLS,
		XPAR_RGB_TO_YUV422_VSC_MAX_ROWS,
		XPAR_RGB_TO_YUV422_VSC_MAX_DATA_WIDTH,
		XPAR_RGB_TO_YUV422_VSC_PHASE_SHIFT,
		XPAR_RGB_TO_YUV422_VSC_SCALE_MODE,
		XPAR_RGB_TO_YUV422_VSC_TAPS,
		XPAR_RGB_TO_YUV422_VSC_ENABLE_420
	}
};


