
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_hscaler.h"

/*
* The configuration table for devices
*/

XV_hscaler_Config XV_hscaler_ConfigTable[XPAR_XV_HSCALER_NUM_INSTANCES] =
{
	{
		XPAR_RGB_TO_YUV422_HSC_DEVICE_ID,
		XPAR_RGB_TO_YUV422_HSC_S_AXI_CTRL_BASEADDR,
		XPAR_RGB_TO_YUV422_HSC_SAMPLES_PER_CLOCK,
		XPAR_RGB_TO_YUV422_HSC_NUM_VIDEO_COMPONENTS,
		XPAR_RGB_TO_YUV422_HSC_MAX_COLS,
		XPAR_RGB_TO_YUV422_HSC_MAX_ROWS,
		XPAR_RGB_TO_YUV422_HSC_MAX_DATA_WIDTH,
		XPAR_RGB_TO_YUV422_HSC_PHASE_SHIFT,
		XPAR_RGB_TO_YUV422_HSC_SCALE_MODE,
		XPAR_RGB_TO_YUV422_HSC_TAPS,
		XPAR_RGB_TO_YUV422_HSC_ENABLE_422,
		XPAR_RGB_TO_YUV422_HSC_ENABLE_420,
		XPAR_RGB_TO_YUV422_HSC_ENABLE_CSC
	}
};


